spring:
   application:
    name: TaskSpringData
   datasource:
     url: ${POSTGRES_HOST}
     username: ${POSTGRES_USER}
     password: ${POSTGRES_PASSWORD}

   jpa:
     hibernate:
       ddl-auto: none
   liquibase:
     enabled: true
     change-log: classpath:/db.changelog/db.changelog-master.yaml
     default-schema: public
logging:
  level:
    liquibase: DEBUG
    org:
      springframework:
        security: DEBUG

server:
  port: 8080